from urban_energy_core.config import *
from urban_energy_core.domain import Building, City, DA, EnergyEntity, FSA, SpatialUnit
from urban_energy_core.integrations import (
    build_hub_ready_building_table,
    build_synpop_city_manifest,
    build_synpop_da_input_table,
    default_hub_repo_root,
    export_hub_building_geojson,
    merge_synpop_summary_to_da_input,
    summarize_synpop_outputs_by_da,
    to_hub_city,
)
from urban_energy_core.io import (
    combine_montreal_building_sources,
    load_all_da_census,
    load_all_fsa_census,
    load_and_prepare_electricity_4cities,
    load_city_da_geojsons,
    load_city_fsa_geojsons,
    load_city_weather_csvs,
    load_montreal_building_geometry,
    load_montreal_building_inventory,
    load_processed_da_electricity_wide,
    load_processed_electricity_wide,
    load_weather_csv,
    save_processed_electricity_wide,
)
from urban_energy_core.plotting import plot_spatial_samples_with_basemap
from urban_energy_core.pipelines import (
    CityBuildResult,
    CoreProjectData,
    ElectricityRebuildResult,
    build_cities_from_data,
    build_city_bundle_from_processed_electricity,
    clean_weather_tables,
    compute_and_attach_city_tables,
    load_core_project_data,
    project_root,
    rebuild_electricity_with_weather_and_imputation,
)

__all__ = [
    "Building",
    "City",
    "DA",
    "EnergyEntity",
    "FSA",
    "SpatialUnit",
    "build_hub_ready_building_table",
    "build_synpop_city_manifest",
    "build_synpop_da_input_table",
    "default_hub_repo_root",
    "export_hub_building_geojson",
    "merge_synpop_summary_to_da_input",
    "to_hub_city",
    "summarize_synpop_outputs_by_da",
    "CoreProjectData",
    "CityBuildResult",
    "ElectricityRebuildResult",
    "build_cities_from_data",
    "build_city_bundle_from_processed_electricity",
    "clean_weather_tables",
    "compute_and_attach_city_tables",
    "load_core_project_data",
    "project_root",
    "rebuild_electricity_with_weather_and_imputation",
    "combine_montreal_building_sources",
    "load_all_da_census",
    "load_all_fsa_census",
    "load_and_prepare_electricity_4cities",
    "load_city_da_geojsons",
    "load_city_fsa_geojsons",
    "load_city_weather_csvs",
    "load_montreal_building_geometry",
    "load_montreal_building_inventory",
    "load_processed_da_electricity_wide",
    "load_processed_electricity_wide",
    "load_weather_csv",
    "save_processed_electricity_wide",
    "plot_spatial_samples_with_basemap",
]
